version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-localhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-localhost
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Admin@123
